# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prostor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSpr', models.IntegerField()),
                ('vzdalenost', models.FloatField()),
                ('popis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRez', models.IntegerField()),
                ('datumVytvoreni', models.DateTimeField(default=datetime.datetime.now)),
                ('datumStrelby', models.DateTimeField()),
                ('idSpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Prostor')),
            ],
        ),
        migrations.CreateModel(
            name='Strelba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStr', models.IntegerField()),
                ('zacatek', models.DateTimeField()),
                ('konec', models.DateTimeField()),
                ('idSpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Prostor')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idZak', models.IntegerField()),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('datum_narozeni', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idZam', models.IntegerField()),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('datum_narozeni', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zbran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idZbr', models.IntegerField()),
                ('nazev', models.CharField(max_length=30)),
                ('typ_zbrane', models.CharField(max_length=30)),
                ('raze', models.FloatField()),
                ('rok_vyroby', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='strelba',
            name='idZak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Zakaznik'),
        ),
        migrations.AddField(
            model_name='strelba',
            name='idZam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Zamestnanec'),
        ),
        migrations.AddField(
            model_name='strelba',
            name='idZbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Zbran'),
        ),
        migrations.AddField(
            model_name='rezervace',
            name='idZak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Zakaznik'),
        ),
        migrations.AddField(
            model_name='rezervace',
            name='idZbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strelnice.Zbran'),
        ),
    ]
